### ISSUE TITLE
Crear la estructura básica del proyecto en Flask - 2

### ISSUE THREAD

**Issue by PabloCorbCon** [pythonmurcia/gitcollab#1]
**Lá página web de GitCollab va a ser creada utilizando el microframework de Flask.**
Necesitamos la creación de la estructura básica de un proyecto en Flask. Es decir, un módulo de Python llamado `app.py` en el root del repositorio, con los diferentes paquetes necesarios para iniciar una aplicación de Flask. 
**También debes crear la ruta del home** utilizando el decorador `@Flask().route()`, de momento esta ruta no tiene que renderizar ningun template.
**Crea los directorios `static/` y `templates` de la aplicación**
[En este artículo puedes leer más sobre un proyecto básico en Flask](https://j2logo.com/leccion-1-la-primera-aplicacion-flask/)

**Comment by JuanjoSalvador** [comment]
¿Solo es necesario crear una ruta de home? Entiendo que posteriormente se deberán añadir el resto de rutas. Pero para una buena planificación inicial, quizás deberíamos conocer cuántas rutas deberá tener el proyecto.

**Comment by PabloCorbCon** [comment]
La estructura básica de Flask no incluye tan solo el archivo `app.py` donde se almacenará la ruta home, sino el directorio `static/` y todos sus subdirectorios y el directorio `templates/` y todos sus subdirectorios.

Con lo que dices de conocer las rutas, es cierto. Héchale un vistazo a #7
