### ISSUE TITLE
Creación de una función para determinar si un enlace pertenece a github - 3

### ISSUE THREAD

**Issue by janselroa** [pythonmurcia/gitcollab#10]
**crea una función llamada** ``github_link(link):``

la función tiene que ser creada dentro del directorio ``/validations/``
concretamente dentro de un archivo llamado ``/validations/links.py``
la función debe evaluar si el link pertenece a Github

**Ejemplos:**

```py
github_link("twitter.com") - False
github_link("github.com") - True
github_link("youtube.com") - False
github_link("github.com/login") - True```

**Comment by JuanjoSalvador** [comment]
Aprovechando esta issue, añadir unos tests unitarios no estaría de más.

**Comment by PabloCorbCon** [comment]
Si, es buena idea. Deja, creo la tarea para que alguien la haga. ¿Utilizando `doctest`? ¿u otro paquete?

**Comment by JuanjoSalvador** [comment]
Doctest está bien, si.

**Comment by PabloCorbCon** [comment]
Issue creado. #18
