### ISSUE TITLE
Función para encriptar los datos del usuario en la base - 5

### ISSUE THREAD

**Issue by PabloCorbCon** [pythonmurcia/gitcollab#12]
**Crea una función llamada `encrypt()` para encriptar de forma segura los datos de los usuarios en la base de datos** Aunque este sea un proyecto experimental, **todos los datos de los usuarios tienen que ser encriptados correctamente en una base de datos SQL**. 

Crea la función `encrypt()` dentro del directorio `db`, concretamente dentro de un archivo llamado `security.py`, es decir `db/security.py`. La función debe de recibir un dato del usuario (como el nombre o el email) y encriptarlo **utilizando la clave de encriptación que prefieras**, a continuación la función tiene que devolver este dato encriptado.
Una vez haya acabado el plazo del proyecto las claves de encriptación cambiarán y se harán privadas, por lo que la función tiene que ser **escalable**.

No postules a esta tarea si tienes experiencia en bases de datos o encriptación.

**Comment by iracaballero** [comment]
Hola Pablo, perdona por la ignorancia, es mi primer Hacktoberfest. Tengo una duda, ¿el script debe recibir la información desde una base de datos sin encriptar, y escribirla encriptada en una nueva base de datos? ¿O simplemente es una función que reciba el dato, lo encripte y lo devuelva encriptado?

**Comment by PabloCorbCon** [comment]
Necesitamos una función que **encripte el dato dado**, este dato será **pasado como un parámetro**.
Imagina la siguiente función:
```python
def encrypt(data: str):
      # encriptar el parametro data
```
Data es un string, este string podría ser por ejemplo un nombre u correo electrónico.
De esta forma, una vez tengamos la función (o funciones) que inserten datos dentro de las bases de datos podemos llamarlas de la siguiente forma
```python
insert_username(encrypt(username))
```
O por lo menos este es nuestro propósito, antes de crear las funciones para insertar datos dentro de las bases tenemos que acabar la tarea #6.

Espero haberte ayudado, cualquier otra duda no dudes en preguntar.
¡Mucha suerte en el hacktoberfest!
