### ISSUE TITLE
Función para desencriptar los datos de las bases de datos - 5

### ISSUE THREAD

**Issue by PabloCorbCon** [pythonmurcia/gitcollab#13]
**Crea una función llamada `decrypt()` para desencriptar de forma segura los datos de los usuarios en la base de datos** Aunque este sea un proyecto experimental, **todos los datos de los usuarios tienen que ser encriptados y desencriptados correctamente en una base de datos SQL**. 

Crea la función `dencryppt()` dentro del directorio `db`, concretamente dentro de un archivo llamado `security.py`, es decir `db/security.py`. La función debe de recibir un dato del usuario (como el nombre o el email) y desencriptarlo **utilizando la clave de encriptación de la función `encrypt()`.** Vea issue #12 , a continuación la función tiene que devolver este dato desencriptado.
Una vez haya acabado el plazo del proyecto las claves de encriptación cambiarán y se harán privadas, por lo que la función tiene que ser **escalable**.

No postules a esta tarea si tienes experiencia en bases de datos o encriptación / desencriptación.

**Este issue está relaccionado con la tarea #12**

**Comment by iracaballero** [comment]
@PabloCorbCon puedes asignarme esta issue?

**Comment by PabloCorbCon** [comment]
¡Hecho! ¡Buena suerte!
