### ISSUE TITLE
¿Hay intención de implementar el uso de blueprints?

### ISSUE THREAD

**Issue by JuanjoSalvador** [pythonmurcia/gitcollab#15]
Para permitir una mejor escalabilidad y manejabilidad de los diferentes modelos y controladores de la aplicación, el uso de Blueprints sería un acierto. Pero este cambio supondría modificaciones sustanciales de la base de la app.

**Comment by PabloCorbCon** [comment]
Si, lo más probable es que implementemos Blueprints. @SEDWI confirmanos esto por favor.

No llego a comprender la frase: 
>"este cambio supondría modificaciones sustanciales de la base de la app."

Lo que no entiendo es la parte de modificaciones sustanciales, es decir; si implementamos planos desde el primer día nos ahorramos las modificaciones que puedan afectar a la escabilidad ¿no?

Tampoco estoy seguro de si algo como #6 es similar a lo que te refieres.

**Comment by JuanjoSalvador** [comment]
Afecta sobretodo a `app.py`, ya que supone cambiar la estructura. Un ejemplo, de una aplicación mía:

https://github.com/JuanjoSalvador/ad-jobs/blob/master/app/__init__.py

Aquí están implementados desde el principio, sobretodo porque tengo un panel de admin separado de la vista pública. Y mediante blueprints, se gestiona todo, como si fuesen sub-aplicaciones dentro de una principal.

**Comment by PabloCorbCon** [comment]
Entiendo esto, personalmente tu crees que las ventajas que pueda tener implementar Blueprints en este proyecto son superiores a las desventajas de modificación?

**Comment by JuanjoSalvador** [comment]
Todo depende de la envergadura del proyecto. Según lo que he visto en las rutas, sería un punto a favor, pero tampoco es algo completamente necesario e imprescindible.
