### ISSUE TITLE
Hacktoberfest en los topics del repositorio (meta)

### ISSUE THREAD

**Issue by JuanjoSalvador** [pythonmurcia/gitcollab#21]
Aunque otros años no ha sido un requisito, este año para que cuenten las PRs enviadas para Hacktoberfest, los repositorios participantes deben tener en los topics la etiqueta "hacktoberfest", tal cual. En caso contrario, aunque se acepten, no contabilizan para la iniciativa.

En este caso, están añadidas las etiquetas "hacktoberfestes" y "hacktoberfest2020", pero no tengo claro que las den como válidas. Son detalles que no parecen estar muy a la vista.

![image](https://user-images.githubusercontent.com/5058655/95022705-31212f80-0679-11eb-8b83-999ace7dede9.png)

**Comment by PabloCorbCon** [comment]
Muchisimas gracias Juanjo, si no llega a ser por tí no nos aceptan nada...

No nos habíamos dado cuenta.
