### ISSUE TITLE
Diseñar la estructura de los errores https - 3

### ISSUE THREAD

**Issue by PabloCorbCon** [pythonmurcia/gitcollab#23]
Los [errores http](https://es.wikipedia.org/wiki/Anexo:C%C3%B3digos_de_estado_HTTP) son una realidad en el mundo de la web, y si están ahí; vamos a hacerlos bonitos...

**Utiliza la plantilla `error.html`, creada en #3 para diseñar una plantilla base que sirva con cada uno de los errores.**

La plantilla tiene que ser capaz de utilizando jinja2 recibir un diccionario `error`, que contiene dos claves (`number` y `description`)
```python
error = {
    "number": "404",
    "description": "No hemos podido encontrar la página que estas buscando"
}
```
Y en base a este diccionario generará la página de cada uno de los errores.

Cada error tendrá una funcion en el archivo `app.py`. Por ejemplo si queremos manejar el error 404 podemos hacer algo como:
```python
@app.errorhandler(404)
def error404(err):
	e = {
		'number':'404',
		'description':'We could not find the page you are looking for, perhaps you have misspelled the link or the page is private.' 
	}
	return render_template('error.html', title='404', error=e), 404
```
Concretamente, tenemos que manejar los errores `400`, `401`, `403`, `404` y `500`

**NOTA IMPORTANTE:** En este issue no se te pide que crees las funciones en el archivo `app.py`para cada uno de los errores que tenemos que manejar, se pide que simplemente diseñes la plantilla de errores a traves de la cual las diferentes funciones la renderizarán para devolverla.

Mira este ejemplo: hay una plantilla `error.html` como ya hemos descrito anteriormente que recibe un diccionario; y recibe un diccionario error para generar las páginas necesarias.

![Screenshot from 2020-10-04 20-03-07](https://user-images.githubusercontent.com/63709477/95023335-c1ad3f00-067c-11eb-8a98-d01fc95a9d5c.png)
![Screenshot from 2020-10-04 20-03-17](https://user-images.githubusercontent.com/63709477/95023339-c70a8980-067c-11eb-8cd0-c17825938668.png)
![Screenshot from 2020-10-04 20-03-23](https://user-images.githubusercontent.com/63709477/95023344-d25db500-067c-11eb-86fc-528a80206486.png)
![Screenshot from 2020-10-04 20-03-31](https://user-images.githubusercontent.com/63709477/95023347-d7226900-067c-11eb-86c1-eccdd9cba5a3.png)
![Screenshot from 2020-10-04 20-03-39](https://user-images.githubusercontent.com/63709477/95023351-db4e8680-067c-11eb-869c-0dad876d0114.png)

**Comment by JuanjoSalvador** [comment]
Al turrón con esta.

**Comment by PabloCorbCon** [comment]
Ve un poco por donde quieras!
Hombre, no utilices un framework "deprecated" (no estoy seguro de cual es la palabra en Castellano, ¿quizás "obsoleto"?) pero por el resto usa el que quieras.

**Comment by JuanjoSalvador** [comment]
Perfecto. Tenía en mente usar Bulma como base (que soy muy fan de esta librería) y sobre eso, ir modificando componentes para adecuarlo.
